# Site settings
author: Gabby Amparo
title: 
header-img: img/home-bg.png
email: gabbyamparo97@gmail.com
copyright_name: Gabby Amparo
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  data-gab

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
